### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by IamSAB** [misibo/event-tool#14]
Ich habe gedacht, wir machen es ganz eifach mit acces control:

- benutzer ist admin oder nicht, d.h wenn er admin ist, kann gruppen und events managen. Zusätzlich kann er auch benutzer bearbeiten, z.b passwort einfach so setzen, email ändern oder jemand zum admin machen (hier könnte man auch einen superadmin machen, welchem nicht das adminrecht von anderen admins entzogen werden kann). Dazu müssen wir nur eine admin column zur db hinzufügen (bool oder smallint im falle eines superadmins).
- als mitglied einer gruppe kann man drei rollen haben: zuschauer, teilnehmer oder leiter. Dafür fügen wir many-to-many table eine role column hinzu. Falls jemand leiter ist, kann er die gruppe bearbeiten, zusätzlich kann er events hinzufügen (er kann auch andere gruppe zum event hinzufügen, damit haben auch die leiter der anderen gruppe rechte für den event) und bearbeiten. als zuschauer kann man sich nicht für einen event anmelden und evtl. auch die teilnehmer nicht sehen (z.b für eltern, damit sie die infos auch haben). als organisatoren für einen event sind leiter der jeweiligen gruppen möglich (dafür müsst man eine zweiteilige form machen).
- eingeloggte benutzer haben ein dashboard, das ihnen einen überblick der gejointed gruppen und angemeldete events gibt. zusätzlich können sie ihr profil bearbeiten

Ich glaube, dass wäre eine ziemlich einfache lösung um den zugriff zu regeln. wir müssten nur zwei columns zu bestehenden db hinzufügen. was meinst du?

**Comment by goldminer77** [comment]
Ich habe mir auch Gedanken gemacht, hier ist ein alternativer Vorschlag.
Im Gegensatz zu deinem Design sieht mein Design in einer Gruppe nicht eine Organisationseinheit, sondern nur als eine Liste von Interessenten, die der Organisator zu einem Event einladen kann. 

Ein Benutzer kann Standard, Leiter, Admin oder Super-Admin sein.

Ein Standard-Benutzer darf folgendes:
- Gruppe beitreten als Zuschauer oder Teilnehmer
- Eigenes Profil bearbeiten

Ein Leiter darf folgendes:
- Events erstellen und Gruppen zu einem Event einladen
- Einladung-Mails verschicken
- Teilnehmerliste eines Events anschauen

Ein Admin darf folgendes:
- Gruppen erstellen und bearbeiten
- Standard-Benutzer zu Leiter machen.
- Passwort setzen, E-Mails ändern, etc.

Ein Super-Admin kann
- Benutzer zu Admins machen

Ein Leiter kann alle anderen Events sehen, bearbeiten und löschen (auch von anderen Leitern). Ich denke, im kleinen Rahmen funktioniert das gut. Später können wir eine Erweiterung nachliefern: Wenn ein Leiter ein Event erstellt, kann nur er diesen Event bearbeiten, ausser er fügt weitere Organisatoren hinzu.

**Comment by IamSAB** [comment]
Ich kann mich nicht entscheiden, was wir nehmen sollen. Deine ist einfacher, meine aber restriktiver in den Rechten. Deine fordert keine Organisation in Gruppen (d.h man könnte auch eine Gruppe Lager oder so machen), meine nimmt diese an (reale Gruppe). Ist mehr eine Frage der Präferenz oder was einem "logischer" erscheint.

**Comment by goldminer77** [comment]
Lass uns deine Lösung nehmen.

- Ist es ok, wenn nur Admins neue Gruppen erstellen können, oder benötigen wir eine Stufe zwischen Admin und Standard?
- Falls wir super-admins haben, macht es evtl. Sinn, Admins ein bischen einzuschränken: Nur ein Super-Admin kann jemand zum Admin machen, Admins können nicht Passwörter und E-Mails von anderen Admins bearbeiten.

**Comment by IamSAB** [comment]
Ok, machen wir das so.

- ja das ist gut so, eine zwischenstufe ist nicht nötig
- macht sinn, man könnte sogar machen, dass nur super admins passwörter ändern können (von allen nutzer)

**Comment by goldminer77** [comment]
Macht Sinn, dann machen wir, dass nur Super-Admins Passwörter und E-Mail-Adressen ändern können.

**Comment by IamSAB** [comment]
**Todos**

User:
- [x] Add role colum (EnumField) with [SuperAdmin, Admin, User] to User model

Member:
- [x] Turn usergroup-relation table into a model
- [x] Add role column (EnumField) with [Leader, Member, Spectator] to Member model

Authorization:
- [ ] Create decorator which has_access()

**Comment by goldminer77** [comment]
Ich habe mir Gedanken gemacht (auch bzg. Dashboard), und ich würde nun doch lieber mein System verwenden. Dein System ist kompliziert zu implementieren, insbesondere die Berechtigungen. Bei meinem System kann man das Dashboard recht einfach gestalten. Das Dashboard muss dann nur einen Stream von Events anzeigen, mit einem Gruppen-Filter, wo jede Gruppe zwei Buttons hat: "beitreten" und "zuschauen". Die Berechtungen wären sehr einfach zu realisieren, weil Leiter auf alle Events Zugriff haben. Wäre das in Ordnung für dich?

**Comment by IamSAB** [comment]
Wo wird es denn genau kompliziert?

Grundsätzlich werden nur die Queries aufwändiger, da man neben dem Benutzerrollen noch die Mitgliederrollen checken muss. Wenn man zb alle Gruppen-Id's, wo der Nutzer ein Leiter ist, im User speichert, wird das ganze noch einfacher bzw. hat sofort alle editierbaren gruppen und damit verbundene events.

**Comment by IamSAB** [comment]
Die event und group manage seiten muss man einfach noch anpassen auf editierbare gruppen und events. das dashboard zeigt infos zu bereits beigetretenen gruppen und deren events. für neue gruppen habe ich eine öffentliche route 'group.groups' gemacht.
